import './globals.css'
import { Inter, Sulphur_Point } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const sulphur_point = Sulphur_Point({
  subsets: ['latin'],
  variable: '--font-sulphur-point',
  weight: ["300", "400", "700"]
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sulphur_point.className} bg-navy`}>{children}</body>
    </html>
  )
}
